### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tatarincev** [comment]
To which issue do these change related?

**Comment by ghost** [comment]
To this particular issue https://github.com/VirtoCommerce/vc-module-order/issues/12

**Comment by tatarincev** [comment]
I think you got the wrong repository. You should do PR there  https://github.com/VirtoCommerce/vc-module-order

**Comment by ghost** [comment]
Nope. Why this? I've made no changes in this one.

**Pull request closed without merging**
